const apis = {
  //新增或编辑学届
  checkSchedule:{
    api:"/api/services/app/basic/AddorUpdateAcademicYear",
    method:"POST",
    isBody:true
  },
  //删除学届
  delSchedule:{
    api:"/api/services/app/basic/DeleteAcademicYear",
    method:"DELETE",
  },
  //学届列表
  scheduleList:{
    api:"/api/services/app/basic/GetAcademicYearPageList",
    method:"POST",
    isBody:true
  },
  //新增或删除国籍
  checkNational:{
    api:"/api/services/app/basic/AddOrUpdateNationality",
    method:"POST",
    isBody:true
  },
  //国籍列表
  nationalList:{
    api:"/api/services/app/basic/GetNationalityList",
    method:"GET"
  },
  //删除国籍
  delNational:{
    api:"/api/services/app/basic/DeleteNationality",
    method:"DELETE"
  },
  //新增或编辑校区
  checkSchool:{
    api:"/api/services/app/basic/AddOrUpdateSchoolZone",
    method:"POST",
    isBody:true
  },
  //校区列表
  schoolList:{
    api:"/api/services/app/basic/GetSchoolZonePPageList",
    method:"POST",
    isBody:true
  },
  //删除校区
  delSchool:{
    api:"/api/services/app/basic/DeleteSchoolZone",
    method:"DELETE"
  },
  //新增或编辑班级
  checkClass:{
    api:"/api/services/app/basic/AddOrUpdateClasses",
    method:"POST",
    isBody:true
  },
  //班级列表
  classList:{
    api:"/api/services/app/basic/GetClassesPageList",
    method:"POST",
    isBody:true
  },
  //删除班级
  delClass:{
    api:"/api/services/app/basic/DeleteClasses",
    method:"DELETE",
  },
  //获取班级详情
  classDetail:{
    api:"/api/services/app/basic/GetClassesDetails",
    method:"GET"
  },
  config:{
    api:"/api/services/app/basic/GetBasicConfig",
    method:"GET"
  }
}

export default apis;
