const apis = {
  //新增或编辑学生
  checkStudent:{
    api:"/api/services/app/family/AddOrUpdateStudent",
    method:"POST",
    isBody:true
  },
  //删除学生
  delStudent:{
    api:"/api/services/app/family/DeleteStudent",
    method:"DELETE",
    isBody:false
  },
  //获取学生详情
  studentDetail:{
    api:"/api/services/app/family/GetStudentDetails",
    method:"GET",
    isBody:false
  },
  //学生列表
  studentList:{
    api:"/api/services/app/family/GetChildList",
    method:"POST",
    isBody:true
  },
  //新增或编辑家长
  checkParents:{
    api:"/api/services/app/family/AddOrUpdateGuardian",
    method:"POST",
    isBody:true
  },
  //删除家长
  delParents:{
    api:"/api/services/app/family/DeleteGuardian",
    method:"DELETE",
    isBody:false
  },
  //获取家长详情
  parentsDetail:{
    api:"/api/services/app/family/GetGuardianDetails",
    method:"DELETE",
    isBody:false
  },
  //家长列表
  parentsList:{
    api:"/api/services/app/family/GetGuardianList",
    method:"POST",
    isBody:true
  },
  //家长选项
  parentsConfig:{
    api:"/api/services/app/family/GetContainGuardList",
    method:"GET",
    isBody:false
  },
  //获取班级选项
  classConfig:{
    api:"/api/services/app/basic/GetClassesListBySchoolZone",
    method:"POST",
    isBody:true
  }
};

export default apis;
